apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod1
  name: mypod1
spec:
  containers:
  - image: centos:7
    name: mypod1
    command: ["/bin/sleep", "3650d"]
    resources: {}
  nodeSelector:
          gpu: "false"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
