apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: centos:7
    name: mypod
    command: ["/bin/sleep", "3650d"]
    resources: {}
  nodeSelector:
          gpu: "true"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
